#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zadanie1802?serverTimezone=Europe/Warsaw&createDatabaseIfNotExist=true
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update